### ISSUE TITLE
Phantom cursor jumps to end of document

### ISSUE THREAD

**Issue by christhekeele** [ThaumRystra/DiceCloud#156] opened 2018-01-30 22:08 UTC
After a few months of heavy usage, I've noticed that when typing any long corpus, my cursor will jump to just after the last character in the document sporadically (every 50 words or so, little rhythm to it).

I've only *noticed* this happening in markdown inputs, on Chrome browsers (both OSX and Chromebook) (so probably not like a touchpad brush thing). It's pretty aggravating but rare enough I haven't spoken up til now. I do most of my actual composition in my editor now.

**Comment by mommothazaz123** [comment] 2018-02-04 22:49
Reproduced on Chrome 63.0.3239.132 on a Windows 10 desktop machine

**Comment by SethForrest** [comment] 2018-02-12 18:49
I get this same error. Also Chrome (v. 64.0.3282.140) and windows 10.
I thought it was the suckey touchpad on my laptop, but it only seems to happen in Dicecloud.

**Comment by ThaumRystra** [comment] 2018-02-14 08:09
I haven't been able to reproduce this yet. Usually the problem with cursors jumping around a field while it's being edited is that the data backing up the field changes, either because the current input is saved, or someone else is also editing the value. This then re-writes the value of the input field, and pushes your cursor to the end sometimes, but not always.

Most input fields should only save the entered value on the "input" event (see [here](https://github.com/ThaumRystra/DiceCloud1/blob/master/rpg-docs/client/views/character/features/featureDialog/featureDialog.js#L89)).

It's possible that changing all inputs to use a "change" event instead will solve this, since "change" will only fire when the element loses focus, preventing it messing with your cursor.

Once I can reproduce the issue I will experiment with this fix.

**Comment by christhekeele** [comment] 2018-02-15 02:31
If it helps, I think it happened the most to me on inputs in the Journal tab.

I assumed it was just because that's where I typed long corpuses the most, so it was more likely to fire... but if events handlers are bound differently to different inputs it may be relevant.

**Comment by sdaugherty** [comment] 2018-02-24 06:25
I'm seeing this fairly often in firefox ( 59.0b12 and previous versions). Seems to happen more often when typing quickly.

**Comment by ThaumRystra** [comment] 2018-03-11 08:50
So I've tried to fix this with change events instead of input events, but [this issue](https://github.com/PolymerElements/paper-input/issues/566) in Polymer's paper-textarea means that it just breaks all the long-format text boxes. Will need to try a different approach

**Comment by foul-fortune-feline** [comment] 2019-10-08 03:57
[This](https://github.com/PolymerElements/paper-input/issues/566#issuecomment-339711196) issue suggests a solution. Your reply here suggests you tried it, but the solution didn't work. As I didn't personally experience *that* issue in particular (tho I have experienced this one), I don't feel right adding that to it. But if *you* have, *you* should, as this is the worst issue most people have experienced with dicecloud. As a developer, you should know how important bug reporting is and the bystander effect has never helped anyone. #

**Comment by foul-fortune-feline** [comment] 2019-10-08 05:59
Okay, actual helpful comment minus salt: Seems to be worse the slower one types (probably the main reason it seemed worse on my phone). Sorry for being bitter but this issue seems to be getting (blatantly) ignored.

**Comment by ThaumRystra** [comment] 2019-10-08 10:43
This issue is being blatantly ignored. It is a bigger deal than just events failing to fire correctly, and I have sunk over 2 weeks of my life into trying to reproduce and fix it.

It might be an easy answer, it might be a quick fix, it might be something I'm missing, but I'm not putting more hours into it at this point. It doesn't happen on my machine at all, and I can't get it to happen consistently enough on other devices I have access to to debug the actual causes.

I understand the salt, but at this point all my energy is on version-2, which doesn't have this issue, and the sooner that becomes the stable version of DiceCloud the sooner this issue can be closed and never haunt me again.

Pull requests welcome.

**Comment by christhekeele** [comment] 2019-10-08 18:04
As someone who can repro this fairly regularly, @ThaumRystra LMK w/e you have a beta of v2 ready enough for me to see if it is gone! Thanks for the great work on my favorite character sheet site.

**Comment by ThaumRystra** [comment] 2019-10-14 08:23
Current v2 build is being hosted at https://alpha.dicecloud.com not even slightly stable yet, but you can poke it anyway.

**Comment by ThaumRystra** [comment] 2020-05-14 10:02
> @ThaumRystra LMK w/e you have a beta of v2 ready enough for me to see if it is gone!

V2 beta is out @christhekeele, let me know if you aren't a patron and I'll send you an invite.

Fixed in #184.

**Closed by ThaumRystra** 2020-05-14 10:02 UTC
Labels: bug, high priority
