### ISSUE TITLE
Disadvantage Effect cannot affect attack rolls

### ISSUE THREAD

**Issue by toonn** [ThaumRystra/DiceCloud#352] opened 2024-04-28 19:24 UTC
I'm playing a Duergar, according to the [Sword Coast Adventurer's guide](http://dnd5e.wikidot.com/lineage:duergar) and I'm trying to implement a certain feature:

> **Sunlight Sensitivity.** You have disadvantage on Attack rolls and Wisdom (Perception) checks that rely on sight when you, the target of your attack, or whatever you are trying to perceive is in direct.

I've implemented a Toggle for whether or not I'm affected by direct sunlight, the Toggle has a Branch and if the toggle is active an Effect is applied, which is Disadvantage affecting the perception stat.

This part works well. However, I can't figure out how to have the effect apply to attack rolls on the Actions tab. The Disadvantage effect only seems able to affect stats?

P.s.: I can't seem to figure out how to "roll" a hit die. Everything else on the Dicecloud sheet seems to conveniently allow triggering a roll, attacks, spells, ability checks but for the life of me I can't get it to roll me a hit die and add the result to my HP.

**Comment by toonn** [comment] 2024-04-30 16:17
It's possible #329 would resolve this but I can't read Discord.

**Comment by toonn** [comment] 2024-05-18 20:22
> P.s.: I can't seem to figure out how to "roll" a hit die. Everything else on the Dicecloud sheet seems to conveniently allow triggering a roll, attacks, spells, ability checks but for the life of me I can't get it to roll me a hit die and add the result to my HP.

This seems to be addressed by the Automatic Hit Die extension.

**Comment by ThaumRystra** [comment] 2024-08-19 08:59
Closed as duplicate of #329

**Closed as completed by ThaumRystra** 2024-08-19 08:59 UTC
